# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5d403adf59993326a0c9b527d08e62b12edac32c8b1e204d0e458ed5bbdb354080431127b2766746fe2a4828aa672883b8dc48eba72dafe3fe2125291a2c6de

test:
  secret_key_base: 69015836e6bb888558a90d302a2f5ca4f9675232d945c35cea127b280098046c0f83147bbe2d3c84face7cb1bf0cf57d2b715ebdce67472d689f460c14290694

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
